version: "3.8"
services:
  web:
    image: acim/go-reflex
    environment:
      - RACE_DETECTOR=1
      - BUILD_ARGS=./cmd/api/main.go
    container_name: banking-system
    ports:
      - 9191:9191
    depends_on:
      - postgres
    volumes:
      - ./:/app

  postgres:
    image: postgres
    restart: always
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: banking-system
